### ISSUE TITLE
how does it work with scss ?

### ISSUE THREAD

**Issue by bcw104** [sencha/extjs-reactor#100]

**Comment by markbrocato** [comment]
To use scss, create a custom theme and apply it to your project using the reactor-webpack-plugin's theme config.  For an example, check out the material-ui boilerplate, which uses a custom theme: https://github.com/sencha/extjs-reactor/tree/master/packages/reactor-material-ui-boilerplate

Creating a custom theme:
(https://docs.sencha.com/extjs/6.2.1/guides/core_concepts/theming.html)

Configuring your theme using reactor-webpack-plugin:
https://github.com/sencha/extjs-reactor#building
