### ISSUE TITLE
Best way to implement mouse events

### ISSUE THREAD

**Issue by BlaineBradbury** [sencha/extjs-reactor#102]
Implementing a simple hover to show a clear X in a TextField, I encountered the need for mouse events.  Is afterRender the place to do this work?  The onChange event fires as shown.  The onMouseOver does not fire, but it does inside the AfterRender method.

```
<TextField
    itemId='TxtMyField'
    triggers={{
        clear: {
            cls: 'x-form-clear-trigger',
            handler: function () {
                this.setValue('');
            }
        }
    }}
    hideTrigger={true}
    onChange={() => this.myFavMouseEvent()}
    onMouseOver={() => this.myFavMouseEvent()}
    onAfterRender={
        (me, eOpts) => {
            me.getEl().on('mouseover', function () {
                me.setHideTrigger(false)
            })
            me.getEl().on('mouseout', function () {
                me.setHideTrigger(true)
            })
        }
    }
/>
```

**Comment by markbrocato** [comment]
You can use the alternate form of event listeners:

```jsx
<TextField onMouseOver={{ element: 'el', fn: myHandler }}/>
```

This is derived from http://docs.sencha.com/extjs/6.2.1/classic/Ext.util.Observable.html#method-addListener

**Comment by BlaineBradbury** [comment]
interesting... am I correct in reading that this callback fn: is an instance of fireEvent which would give 'myHanlder' (eventName, args)?
re: http://docs.sencha.com/extjs/6.2.1/classic/Ext.util.Observable.html#method-fireEvent

Maybe not... From 'myHandler' I am seeing what looks like the event itself and the target dom element.  With this alternate method, how would I address the underlying component to perform an operation like "me.setHideTrigger(false)" from above?

I came up with this:
```
        Ext.getCmp(Ext.get(target).parent().parent().id).setHideTrigger(false)
```
...but getting the parent from the target is only defined when first entering the field.  Move the mouse a bit more and it is undefined...

...so I hacked a bit and found that this works in 'myHandler'...
```
        if (target.getAttribute('data-ref') === 'triggerWrap') {
            Ext.getCmp(Ext.get(target).parent().parent().id).setHideTrigger(false)
        } else {
            Ext.getCmp(Ext.get(target).getAttribute('data-componentid')).setHideTrigger(false)
        }
```

Works, but is ugly and I don't understand what is happening :)  Guessing I'm bumping up against React rendering.

**Comment by markbrocato** [comment]
How about using React's ref callback like this:

```jsx
<TextField 
	ref={cmp => this.text = cmp}
	onMouseOver={{ 
		element: 'el', 
		fn: () => this.text.setHideTrigger(false)
	}}
/>
```

**Comment by BlaineBradbury** [comment]
Seems like a mixed bag, but probably better than afterRender.
What's the deal with the callback reference?  Do I need to pass it some scope or something?

**Comment by markbrocato** [comment]
The ref prop can applied to any react element.  The supplied function gets called when the element is rendered.  Generally you use it to add references to a composite component in the render method.  See https://facebook.github.io/react/docs/refs-and-the-dom.html

**Comment by BlaineBradbury** [comment]
Yes, I am familiar with the ref part.  My last thought is really trying to figure out how to distribute the business logic from the onMouseOver event to some other shared handler function... some separation of code.  I would prefer something like these...
```
    onMouseOver={{
        element: 'el',
        fn: this.myHandler
    }}
...
    onAfterRender={
        (me, eOpts) => { me.getEl().on('mouseover', this.myHandler) }
    }
```
...instead of these...
```
    onMouseOver={{
        element: 'el',
        fn: () => this.text.setHideTrigger(false)
    }}
...
    onAfterRender={
        (me, eOpts) => { me.getEl().on('mouseover', () => me.setHideTrigger(false) ) }
    }
```
...but the former seems to require more than just a simple obj.setHideTrigger(false) inside myHandler() which seems ugly (re: earlier if/else if/else myHandler example).  Something I'm missing here.

**Comment by markbrocato** [comment]
How about passing a reference to the textfield with something like this?

```jsx
   onMouseOver={{
        element: 'el',
        fn: () => myHandler(this.text)
    }}
```

**Comment by mitchellsimoens** [comment]
Is the issue a scope issue?

**Comment by markbrocato** [comment]
Closing this.  Feel free to continue posting on this thread if you have further questions on this topic.

**Comment by BlaineBradbury** [comment]
@mitchellsimoens I am not sure, but addListener (http://docs.sencha.com/extjs/6.2.1/classic/Ext.util.Observable.html#method-addListener) does have a scope argument to which I have passed various references, but the behavior did not change.  

RE: In the earlier example...
```
    <TextField onMouseOver={{ element: 'el', fn: myHandler }}/>
```
... with this callback ...
```
    myHandler (eventname, target) {
        if (target.getAttribute('data-ref') === 'triggerWrap') {
            Ext.getCmp(Ext.get(target).parent().parent().id).setHideTrigger(false)
        } else if (Ext.get(target).getAttribute('data-ref') === 'inputEl') {
            Ext.getCmp(Ext.get(target).getAttribute('data-componentid')).setHideTrigger(false)
        } else {
            Ext.getCmp(Ext.get(target).parent().parent().parent().id).setHideTrigger(false)
        }
    }
```
...it became clear to me that I am missing some understanding of the complete component lifecycle between what ExtJS is doing and what React is doing.

Essentially, when I pass in myHandler as a callback, the element that shows up when myHandler is executed (what I'm showing as "eventname") is different depending on where the mouse moves.  Sometimes it looks like an event object, sometimes it looks like a dom element, and sometimes it looks like an object containing a dom element.   I can see that the IF statement I am using in myHandler to chase down a reference to componentid did not cover all the cases.  There is a "labelEl" and some other nested versions of the "triggerWrap".  Getting a reference to the component through a ref or some other method seems easier, but it doesn't solve the fuzzy picture in my head.  I'll post here when/if I get time to dig into it.

**Comment by mitchellsimoens** [comment]
@BlaineBradbury basically, what is `this` within the myHandler? Is it the component or is it the element? A couple properties you can check within your handler is `this.isComponent` or `this.isElement`. I'm thinking `this.isElement` is `true` and therefor not scoped to the component.

Once verified there, we can discuss how to better handle this as 95% of the time you'd want it scoped to the component but there are some cases where having it scoped to the element is useful.

**Comment by BlaineBradbury** [comment]
@mitchellsimoens I'm not sure if you mean in the React or Extjs sense of component vs. element.  ```this.isComponent``` and ```this.isElement``` are undefined in myHandler.  I'm not sure where this properties would come from... not familiar.  ```this``` seems to me to be a reference to the React Component itself.  Here is some logging I did that may answer the question though.

```
console.log(this)
console.log(this.isComponent)
console.log(Ext.isElement(this))
```

![comporel](https://cloud.githubusercontent.com/assets/282549/24762384/338afdfc-1abc-11e7-8661-a9ebbcc3e9e4.png)

**Comment by BlaineBradbury** [comment]
Testing on a TextField, I finally understand one difference that should've been obvious earlier.  This doesn't resolve the issue with events declared with the function or arrow function syntax not firing in some cases ( re: #140 ), but it might shed some light on the difference in functionality here.

 ```onChange{this.myHandler}``` attaches a change handler to the form field so that ```myHandler``` receives arguments like ```(field, newValue, oldValue, eOpts)``` as per http://docs.sencha.com/extjs/6.2.1/classic/Ext.form.field.Field.html#event-change

This event fires after each change to the field, so if I type "123" it fires three times while typing.

```onChange{{element: 'el', fn: this.myHandler}}``` and ``` onAfterRender={ (me, eOpts) => me.getEl().on('change', this.onSearchADITextChange ) } ``` attaches a change handler to the DOM element and ```myHandler``` receives a different set of arguments like ```(e , t , eOpts)``` as per http://docs.sencha.com/extjs/6.2.1/classic/Ext.dom.Element.html#event-change

This event fires only after the field loses focus, so if I type "123" nothing happens, but if I click out of the field it fires once.

@mitchellsimoens I'm also wondering if this implicitly answers your question about ```this```?
