### ISSUE TITLE
how to use with NavigationView?

### ISSUE THREAD

**Issue by bcw104** [sencha/extjs-reactor#104]
how to push a Component to the NavigationView?
`import React, {
    Component
} from 'react'
import {
    Container,
    NavigationView,
    Button
} from '@extjs/reactor/modern';

export default class Home extends Component {
    render() {
        return (

            <NavigationView
            title = "Home"
            iconCls = 'x-fa fa-home'
            defaultBackButtonText = ''
            ref = "nav" 
            >
                <Container title="Home" scrollable={true}>
                    <div>hello</div>
                    <Button
                        text="Click Me"
                        ui="action"
                        onTap={() => this.onClick()}
                    >
                    </Button>
                </Container>
            </NavigationView>
        );
    }

    onClick() {
        console.log('click');
        this.refs.nav.push({
            title: 'Hello',
            html: 'hello'
        });
    }
}`

**Comment by markbrocato** [comment]
That would work, but NavigationView doesn't lend itself to the react way because you need imperative calls to push/pop.

How about using a card layout like:

```jsx
import React, { Component } from 'react';
import { Container, Button, TitleBar } from '@extjs/reactor/modern';

export default class NavigationViewExample extends Component {
    
    state = {
        activeItem: 0,
        details: null
    }

    showDetails = () => {
        this.setState({ 
            details: { firstName: 'Tim', lastName: 'Jones' },
            activeItem: 1
        });
    }

    back = () => {
        this.setState({ 
            activeItem: 0
        });
    }

    removeDetails = () => {
        this.setState({ 
            details: null
        })
    }

    render() {
        const { details, activeItem } = this.state;

        return (
            <Container layout={{ type: 'card', animation: { type: 'slide' } }} activeItem={activeItem}>
                <Container title="Home">
                    <TitleBar title="Home" titleAlign="center"/>
                    <Button text="Show Details" handler={this.showDetails}/>
                </Container>
                { details && (
                    <Container onHide={() => this.removeDetails}>
                        <TitleBar title="Details" titleAlign="center">
                            <Button align="left" text="Back" handler={this.back} iconCls="x-fa fa-arrow-left"/>
                        </TitleBar>
                        <div>First Name: {details.firstName}</div>
                        <div>Last Name: {details.lastName}</div>
                    </Container>
                )}
            </Container>
        )
    }

}
```

**Comment by bcw104** [comment]
@markbrocato 
your code can't work correctly. the second container did not show when I click the button.

**Comment by markbrocato** [comment]
Please try updating @extjs/reactor to 0.2.16.

**Comment by bcw104** [comment]
@markbrocato 
tks it works.
