### ISSUE TITLE
Support Concrete component class

### ISSUE THREAD

**Issue by unional** [sencha/extjs-reactor#12]
The prefix hack to override `createInternalComponent` is fragile and does not work with TypeScript.

Would you consider exporting `ExtJSComponent` so it can be used to create concrete ExtJS-react components?

**Comment by markbrocato** [comment]
In general yes, I would like to support creating concrete components.  Let me put some thought into this next week.  I'm not sure if simply exporting ExtJSComponent is the best approach.  Perhaps some sort of intermediate or higher order component is necessary.

**Comment by unional** [comment]
Sure.

By the way, there is a bug here:
https://github.com/sencha/extjs-reactor/blob/master/packages/reactor/src/ExtJSComponent.js#L295

Should use the input prefix.

**Comment by unional** [comment]
I was doing something similar in the past. I can dig into it to see if there is anything I can share. 🌷

**Comment by unional** [comment]
I come from TypeScript perspective, and instead of overriding createInternalComponent, you can consider doing something with `JSX.createElement()` and `JSX.__spread`

Here are some references:
https://basarat.gitbooks.io/typescript/content/docs/jsx/tsx.html
https://www.typescriptlang.org/docs/handbook/jsx.html
https://github.com/Microsoft/TypeScript/pull/6146

**Comment by markbrocato** [comment]
I'm leaning towards providing a factory function that creates a react component wrapper for any Ext JS component.  The API would look something like this:

```javascript
import { reactify } from '@extjs/reactor';

const Grid = reactify('grid'); // by xtype;

function MyComponent(props) {
  return <Grid ... />
}
```

Would that work for you?

**Comment by unional** [comment]
That would be better, without overriding anything.

Just need to make sure the return Grid is a proper react component that can be inherited:

```js
import { reactify } from '@extjs/reactor';
const Grid = reactify('grid');

class CustomGrid extends Grid {
  // provide xtype?
...
}
```

And that it works with custom Ext components.

How does it work with 6.5 classes?
```js
import { define }     from 'extjs-kernel'; // module names not final
import { Observable } from 'extjs-core';
 
import { Base }       from 'app-some';
 
@define({
  mixins: Observable,
  config: {
    value: null
  }
})
export default class Foo extends Base {
  updateValue (value, oldValue) {
    this.fireEvent('valuechange', value, oldValue);
  }
}

const ReactFoo = reactify(Foo);
```

**Comment by markbrocato** [comment]
Yes, the result of reactify will be a react component that you can extend. You will be able to pass an Ext class to reactify.  You will even be able to do this with Ext 6 classes, for example:

```javascript
const ReactGrid = reactify(Ext.grid.Panel);
```

From communicating with the react team, it seems like they are working on a reimplementation of the react-core.  It seems doubtful that the hack to override createInternalComponent is future-proof. The idea of using a factory function instead got their blessing, so I'll most likely remove the install hack soon (v0.2).

**Comment by markbrocato** [comment]
Here is the thread in the react repo related to createInternalComponent, if you're interested:

https://github.com/facebook/react/issues/8358

**Comment by unional** [comment]
Thanks. Seems like a plan.

btw, do you know if ExtJS team would be interested in creating typings (TypeScript definition file) for the ExtJS codebase?

**Comment by markbrocato** [comment]
Possibly.  Do you know if type definitions can cover factory functions like Ext.create({ xtype: 'button' })? If not, I think it would be much easier to create tsd files once Ext classes are also ES6 modules

**Comment by unional** [comment]
Yes, it is possible, but it is better for ES6.
I hope in ES6 the functional pieces would be smaller to chew. `Ext.create()` would be a huge typings and hard to do.

**Comment by unional** [comment]
Just for reference:
https://github.com/Microsoft/TypeScript/issues/9582#issuecomment-260118063

TypeScript and some other libraries do this.

**Comment by markbrocato** [comment]
We've settled on a new syntax for 0.2 to replace the "x-" prefix app.  You can see what the new code will look like in the 0.2 readme:

https://github.com/sencha/extjs-reactor/tree/0.2

In short, you can create a React component for any Ext JS component via a reactify factory function:

```jsx
import { reactify } from '@extjs/reactor';
const Grid = reactify('grid');
```

You'll also be able to import reactified components using ES6 syntax if you use the new @extjs/reactor-babel-plugin.  So the above would look like:

```jsx
import { Grid } from '@extjs/reactor/modern'; // or @extjs/reactor/classic
```

If all goes well 0.2 should be out in the next few weeks.

**Comment by unional** [comment]
Great!
What does `reactor-babel-plugin` do? I'm using TypeScript so probably need to do a path mapping for it.

**Comment by unional** [comment]
If it is open sourced, I can take a look into it.

On the other hand, I can still simply use `reactify()` 🌷

**Comment by markbrocato** [comment]
The source is part of this repo:

https://github.com/sencha/extjs-reactor/tree/0.2/packages/reactor-babel-plugin

The readme contains a simple explanation of how it works.

**Comment by unional** [comment]
I see, forgot that your repo contains packages that way. 😛

**Comment by unional** [comment]
With `reactify()`, my guess is that you don't need to override `createInternalComponent()` (and as it will go away soon as you mentioned).

So the `install()` call will be used only for `viewport` configuration.
Would it be better if it is renamed to reflect that?
Or you want it to be the single entry point to configure all ExtJS related integration?

**Comment by markbrocato** [comment]
You're right, currently `install()` does very little.  Right now it just injects the style for the host div for reactified Ext JS components and some additional CSS if you set `viewport: true`. My thinking was to keep the name "install" so that we could add options as needed to further configure the integration in the future.

**Comment by markbrocato** [comment]
We've published 0.2, which uses the new reactify function and import syntax.  When you get a chance, please check it out and give us your feedback.

**Comment by unional** [comment]
Will do

**Comment by unional** [comment]
I don't like `reactify(...targets)`. I would suggest to keep it simple and do `reactify(target)`.

The consumer does not gain much from doing this "shortcut". It is better to keep it simple. Also, `reactify(...targets)` makes it to hard type and use in TypeScript in the future,when `react` `Property` and `State` can pass down to ExtJS component. 
It also makes the code impossible to use generics.

```ts
import React = require('react')  // You should do this too, CommonJS <-> ESM interop is flawed.
import { reactify } from '@extjs/reactor'

interface GridProperty {}
interface GridState {}
interface GridInterface { }
interface PanelProperty {}
interface PanelState {}
interface PanelInterface { }

const Grid1 = reactify('grid') as GridInterface & React.Component<GridProperty, GridState>

const [ Grid2, Panel ] = reactify('grid', 'panel') as [
  GridInterface & React.Component<GridProperty, GridState>,
  PanelInterface & React.Component<PanelProperty, PanelState>
]

// If using generic, which is what I'm doing:
const Grid3 = reactify<GridInterface, GridProperty, GridState>('grid')
```

I'm using Intersection type `GridInterface & React.Component<...>` because this would allow the consumer to extend the default grid and provide their own property and state.

**Comment by markbrocato** [comment]
You don't have to specify multiple parameters to reactify.  For example

```javascript
const [Grid, Panel] = reactify('grid', 'panel');
```

could be rewritten as 

```javascript
const Grid = reactify('grid');
const Panel = reactify('panel');
```

**Comment by unional** [comment]
Closing this and start #26 as this is resolved with `reactify()`
