### ISSUE TITLE
Ext.ClassManager is undefined

### ISSUE THREAD

**Issue by liam-goodacre-hpe** [sencha/extjs-reactor#129]
I have a project set up with webpack, babel, and the appropriate plugins from this repo.
In the entry point of my program I have:

```javascript
import {install} from "@extjs/reactor"
install({})
```

In a `view.jsx` file, I have:

```javascript
import * as React from 'react'
import {TabPanel} from '@extjs/reactor/classic'
export const view = () =>
  <TabPanel items={[
    {title: 'hello'}
  ]}/>
```

When I go to render the view I get an error in the console: `TypeError: Ext.ClassManager is undefined`.

The `TextField` component appears to work fine, but it's not happy with `TabPanel`.

Is this a bug, or have I done something wrong?

Also, how is a `TabPanel` supposed to be used with nested components?

**Comment by liam-goodacre-hpe** [comment]
Oh, I've broken everything... now if I'm not even using any ExtJS components I still get the `Ext.ClassManager is undefined`.

**Comment by markbrocato** [comment]
That error probably means that cmd is failing to build the extjs bundle.  Is it possible to share you project on GitHub?  If so I'd be happy to take a look at your config.

Regarding the use of TabPanel, or any other component that extends container, items get mapped to the children prop.  So, for example:

```jsx
import * as React from 'react'
import { TabPanel, Panel } from '@extjs/reactor/classic'

export default function View() {
    return (
        <TabPanel>
            <Panel title="Tab 1">
                Tab 1 Content
            </Panel>
            <Panel title="Tab 2">
                Tab 2 Content
            </Panel>
        </TabPanel>
    )
}
```

**Comment by liam-goodacre-hpe** [comment]
Thanks for your help, I had some mix up with configuration and imports.
