### ISSUE TITLE
mouse handler syntax not firing with "inline callbacks"

### ISSUE THREAD

**Issue by BlaineBradbury** [sencha/extjs-reactor#140]
Something seems to have changed since I updated reactor versions.  onChange works no matter which syntax, but onMouse... only fires with the certain methods.

Works:
```
onChange={
     () => console.log('look here')
}
onMouseOut={{
     element: 'el',
     fn: this.myHandler
}}
onAfterRender={
     (me, eOpts) => {
          me.getEl().on('mouseover', () => console.log('here') )
          me.getEl().on('mouseout', () => console.log('here too') )
     }
}
```
Does Not work:
```
onMouseOver={
     () => console.log('look here')
}
onMouseOut={
     function () { console.log('look here') }
}
```

**Comment by BlaineBradbury** [comment]
...and this syntax passes build, but does not fire for me.
```
onKeyUp={ function (key) { console.log(key.getKey()) }
```
nor
```
listeners={{
          'keyup': {
          fn: function (key) { console.log(key.getKey()) }
     }
}}
```
If I use arrow functions, the listeners fails build with a Rhino Parser error:
```
building Ext JS bundle: ext => /Library/WebServer/Documents/path/build/extjs
Sencha Cmd v6.2.1.29
[INF] Loading app json manifest...
[ERR] C2000: Rhino Parse Error (syntax error =>                                 fn: (key) => console.log(key.getKey())) -- /Library/WebServer/Documents/path/build/extjs/manifest.js:525:45
[ERR] C2000: Rhino Parse Error (syntax error =>                         }});) -- /Library/WebServer/Documents/path/build/extjs/manifest.js:527:25
[ERR] C2000: Rhino Parse Error (Compilation produced 2 syntax errors. => null) -- /Library/WebServer/Documents/path/build/extjs/manifest.js:1
[ERR] 
[ERR] BUILD FAILED
[ERR] org.mozilla.javascript.EvaluatorException: Compilation produced 2 syntax errors.
[ERR] 
[ERR] Total time: 2 seconds
[ERR] org.mozilla.javascript.EvaluatorException: Compilation produced 2 syntax errors.
Error: Error building Ext JS bundle
    at /Library/WebServer/Documents/path/node_modules/@extjs/reactor-webpack-plugin/dist/index.js:208:65
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by markbrocato** [comment]
Have you set enableKeyEvents to true?

For example:

```jsx
<TextField enableKeyEvents onKeyUp={this.keyUpHandler}/>
```

**Comment by markbrocato** [comment]
API docs:

http://docs.sencha.com/extjs/6.2.1/classic/Ext.form.field.Text.html#cfg-enableKeyEvents

**Comment by markbrocato** [comment]
The syntax error you encountered when using arrow functions inside of listener config objects should be fixed by updating to v0.2.18 of @extjs/reactor-webpack-plugin.

**Comment by BlaineBradbury** [comment]
enableKeyEvents resolves the ```onKeyUp={}``` not firing!  Is there an enableMouseEvents :)

**Comment by markbrocato** [comment]
There isn't.  To listen for mouse events you need to use the element config to target the inner input element.  For example:

```jsx
<TextField
     onMouseOver={{
         element: 'el',
         fn: () => console.log('over')
     }}
/>
```

See the docs here (scroll down to the "element" option): http://docs.sencha.com/extjs/6.2.1/classic/Ext.mixin.Observable.html#method-addListener

In general you can listen for any event from Ext.dom.Element using this form of event listener.
http://docs.sencha.com/extjs/6.2.1/classic/Ext.dom.Element.html#events

**Comment by BlaineBradbury** [comment]
@markbrocato I had just accomplished my desired goal as I read your last post :)  The element thing had me baffled (#102), but these two options finally got me going.  The buffer was the final need, and that works as below.  Thank you.
 
```
onChange={{
     buffer: 1000,
     fn: this.myHandler,
     args: [{miscArg: 'my string'}]
}}
onMouseOver={{
     element: 'el',
     fn: this.myHandler
}}
```
