### ISSUE TITLE
Unable to start boilerplate

### ISSUE THREAD

**Issue by unional** [sencha/extjs-reactor#17]
I get the 6.2.0 to `ext` folder and followed instructions.
The error I got is:

```sh
λ npm start

> react-session@0.1.13 start e:\hwong\git\extjs-reactor\packages\reactor-classic-boilerplate
> webpack-dev-server --progress --config webpack.config.dev.js --port 8000

 70% 1/1 build modules http://localhost:8000/webpack-dev-server/
webpack result is served from /
content is served from ./build
 90% optimize assets
building Ext JS bundle: ext => build\extjs
Sencha Cmd v6.2.0.103
[WRN] Failed to resolve package theme-triton
[WRN] Failed to resolve package charts
[ERR] Theme "theme-triton" not found
[ERR]
[ERR] BUILD FAILED
[ERR] com.sencha.exceptions.BasicException: com.sencha.exceptions.ExNotFound: Required package "theme-triton" not found
[ERR]
[ERR] Total time: 0 seconds
[ERR] com.sencha.exceptions.BasicException: com.sencha.exceptions.ExNotFound: Required package "theme-triton" not found
```

**Comment by markbrocato** [comment]
Hmm... can you post a screenshot of the ext directory expanded?  It should just be the unzipped SDK you download from sencha.com or the support portal.

**Comment by unional** [comment]
![image](https://cloud.githubusercontent.com/assets/3254987/20725606/4226a590-b627-11e6-8e68-7f51a9f38999.png)

Here is the structure

**Comment by markbrocato** [comment]
You should have packages/charts and classic/theme-triton. Are both of those present under ext?

**Comment by unional** [comment]
Yes I do
![image](https://cloud.githubusercontent.com/assets/3254987/20726009/b75359a2-b628-11e6-873e-91aeeaf513bd.png)
![image](https://cloud.githubusercontent.com/assets/3254987/20726013/bab105a4-b628-11e6-8d4d-cf17fecd2128.png)

**Comment by unional** [comment]
Testing with latest also yield the same result.

**Comment by unional** [comment]
In `reactor-boilerplace` the error is `theme-material` not found. And it is there.

**Comment by markbrocato** [comment]
Hmm... just had someone else try the boilerplate here and it worked just fine.  What OS/shell are you using?

**Comment by unional** [comment]
Windows 2012 and Sencha cmd 6.2.0.103, on cmder. The shell should not matter thou.

**Comment by unional** [comment]
Tried Sencha cmd 6.2.1.29, same result.

**Comment by unional** [comment]
Just in case, tried on powershell, same result

**Comment by markbrocato** [comment]
Looks like it's an issue with Windows.  Probably "\" vs "/".  Looking into it...

**Comment by markbrocato** [comment]
Should be fixed now in v0.2.1.

**Comment by unional** [comment]
Confirmed it is working.

However, there is an error:

```sh
ERROR in ./src/index.js
Module parse failed: e:\hwong\git\extjs-reactor\packages\reactor-boilerplate\src\index.js Unexpected token (15:34)
You may need an appropriate loader to handle this file type.
```

Should `index.js` be `index.jsx`? I'm not familiar with webpack so I don't know what to do to fix that.

**Comment by markbrocato** [comment]
Try running `npm install`.  The upgrade from 0.1 to 0.2 added at least one new module.

**Comment by unional** [comment]
I did that.

It error at `<App/>`, seems like it is not recognizing JSX?

**Comment by unional** [comment]
I change it to `JSX.createElement(App)` and the error goes away, so it must be JSX recognition related.

After that, when it is up (showing `[INF] Waiting for changes...`, `http://localhost:8000` is not up.

**Comment by unional** [comment]
> http://localhost:8000 is not up.

You probably mean <http://localhost:8080>

**Comment by unional** [comment]
Also, that page is black due to errors:
![image](https://cloud.githubusercontent.com/assets/3254987/20734663/d8f6d972-b64f-11e6-8593-f010a74f42fe.png)

**Comment by markbrocato** [comment]
JSX is transpiled by babel via the babel loader and the react preset in .babelrc.  You're running `npm start`, right?

**Comment by unional** [comment]
Yes

**Comment by unional** [comment]
Seems like the transpilation fails, the index.js still has `import`

**Comment by markbrocato** [comment]
What if you run a production build instead?

```bash
npm run build
npm run prod
```

**Comment by unional** [comment]
`npm run build` fail with:
```sh
ERROR in index.js from UglifyJs
SyntaxError: Unexpected token: name (React) [./src/index.js:1,0]
Child html-webpack-plugin for "index.html":
        + 3 hidden modules
```

**Comment by markbrocato** [comment]
Hmm, definitely something funny going on with your environment.  You have a .babelrc file with the following contents, right?

```json
{
  "presets": [
    "es2015",
    "stage-2",
    "react"
  ],
  "plugins": [
    "@extjs/reactor-babel-plugin"
  ]
}
```

**Comment by unional** [comment]
> You probably mean http://localhost:8080?

To clarify, it is correct. `reactor-boilerplate` uses 8080, while `reactor-classic-boilerplate` uses 8000

**Comment by unional** [comment]
Yes.

**Comment by unional** [comment]
For `reactor-classic-boilerplate`, the error is the same (not recognizing JSX) for `npm start` and `npm run build`

**Comment by unional** [comment]
^ well, that's because I didn't make the change `<App/> -> JSX.createElement(App)` there.

**Comment by unional** [comment]
Let me also test it on OSX

**Comment by markbrocato** [comment]
Maybe it's not picking up .babelrc for some reason?  

Try added presets via the query on the babel loader in webpack.config.dev.js and rerun npm start:

```javascript
{
    test: /\.js$/,
    loader: 'babel',
    query: {
        presets: [
            "es2015",
            "stage-2",
            "react"
        ],
        plugins: [
            "@extjs/reactor-babel-plugin"
        ]
    },
    include: [
        path.join(__dirname, 'src')
    ]
},
```

**Comment by unional** [comment]
Nope, same error. Really strange.

**Comment by markbrocato** [comment]
What do you get for `npm list babel-loader`?

**Comment by unional** [comment]
6.2.8

**Comment by markbrocato** [comment]
Same here.  Were you able to get it working on OSX?

**Comment by unional** [comment]
It is working on OSX

**Comment by unional** [comment]
by the way, my ultimate goal is to able to develop this with TypeScript and jspm.

**Comment by unional** [comment]
I can see it failed to parse in `NormalModule.js` of webpack. Adding a log there:

```sh
λ npm run build

> @extjs/reactor-boilerplate@0.2.0 build e:\hwong\extjs-reactor\packages\reactor-boilerplate
> npm run clean && webpack --config webpack.config.prod.js --progress --profile --colors


> @extjs/reactor-boilerplate@0.2.0 clean e:\hwong\extjs-reactor\packages\reactor-boilerplate
> rimraf build

 40% 1/2 build modulesModuleParseError with: e:\hwong\extjs-reactor\packages\reactor-boilerplate\src\index.js
742ms build modules
0ms seal
0ms optimize
0ms hashing
16ms create chunk assets
47ms additional chunk assets
0ms optimize chunk assets
 90% optimize assets
building Ext JS bundle: ext => E:\hwong\extjs-reactor\packages\reactor-boilerplate\build\extjs
Sencha Cmd v6.2.1.29
[INF] Loading app json manifest...
[INF] Writing concatenated output to file E:\hwong\extjs-reactor\packages\reactor-boilerplate\build\extjs\ext.js
[INF] Appending concatenated output to file E:\hwong\extjs-reactor\packages\reactor-boilerplate\build\extjs\ext.js
[INF] writing sass content to ext.scss
[INF] appending sass content to ext.scss
[INF] appending sass content to ext.scss
[INF] merging 372 input resources into E:\hwong\extjs-reactor\packages\reactor-boilerplate\build\extjs\resources
[INF] merged 371 resources into E:\hwong\extjs-reactor\packages\reactor-boilerplate\build\extjs\resources
[INF] merging 6 input resources into E:\hwong\extjs-reactor\packages\reactor-boilerplate\build\extjs\resources
[INF] merged 6 resources into E:\hwong\extjs-reactor\packages\reactor-boilerplate\build\extjs\resources
[LOG] Building E:/hwong/extjs-reactor/packages/reactor-boilerplate/build/extjs/ext.scss
Exiting with code 0

10192ms optimize assets
0ms emit
Hash: d5ea1a0c465c40eb75a2
Version: webpack 1.13.3
Time: 11013ms
       Asset       Size  Chunks             Chunk Names
    index.js  320 bytes       0  [emitted]  main
index.js.map   99 bytes       0  [emitted]  main
  index.html  481 bytes          [emitted]
   [0] multi main 28 bytes {0} [built] [1 error]
       factory:0ms building:0ms = 0ms
   [1] ./src/index.js 0 bytes [built] [failed]
       [0] 0ms -> factory:30ms = 30ms

ERROR in ./src/index.js
Module parse failed: e:\hwong\extjs-reactor\packages\reactor-boilerplate\src\index.js Unexpected token (15:34)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (15:34)
...
```

Relevant transpiled `NormalModule.js`:

```js
NormalModule.prototype.build = function build(options, compilation, resolver, fs, callback) {
	this.buildTimestamp = new Date().getTime();
	this.built = true;
	return this.doBuild(options, compilation, resolver, fs, function(err) {
		if(err) return callback(err);
		this.dependencies.length = 0;
		this.variables.length = 0;
		this.blocks.length = 0;
		this._cachedSource = null;
		if(options.module && options.module.noParse) {
			if(Array.isArray(options.module.noParse)) {
				if(options.module.noParse.some(function(regExp) {
						return typeof regExp === "string" ?
							this.request.indexOf(regExp) === 0 :
							regExp.test(this.request);
					}, this)) return callback();
			} else if(typeof options.module.noParse === "string" ?
				this.request.indexOf(options.module.noParse) === 0 :
				options.module.noParse.test(this.request)) {
				return callback();
			}
		}
		try {
			this.parser.parse(this._source.source(), {
				current: this,
				module: this,
				compilation: compilation,
				options: options
			});
		} catch(e) {
			console.log('ModuleParseError with:', this._source._name)
			var source = this._source.source();
			this._source = null;
			return callback(new ModuleParseError(this, source, e));
		}
		return callback();
	}.bind(this));
};
```

**Comment by markbrocato** [comment]
Does this project work for you on windows? https://github.com/gaearon/react-hot-boilerplate.

At this point I'm thinking you must have stumbled upon an issue with webpack itself unrelated to reactor.

**Comment by unional** [comment]
It is related to this: https://github.com/gaearon/react-hot-boilerplate/issues/75

Need to trace down the rabbit hole.... 😭

**Comment by markbrocato** [comment]
One user in that thread did mention reinstalling node fixed it.  Wouldn't be the first time.  Also just blowing away node_modules and running npm install has been known to fix mysterious issues in the past.

**Comment by unional** [comment]
Upgrade to node 6.9.1 fixed it for me. 🌷

**Comment by unional** [comment]
0.2.3 doesn't work again.

When I made the following change, I can run SenchaCmd:
```js
// build/extjs/workspace.json
{
  frameworks: {
    "ext": "E:\....\ext"  // change to '../../ext' works
  }
}
```

**Comment by unional** [comment]
Nevermind. I saw that your code has made the right fix already. I have to do the same for my ts-plugin
