### ISSUE TITLE
Tab panel with closable panels using activeTab

### ISSUE THREAD

**Issue by liam-goodacre-hpe** [sencha/extjs-reactor#182]
I've created a repo to demonstrate the issue I'm seeing: https://github.com/liam-goodacre-hpe/extjs-reactor-tab-bug

Here are the steps to reproduce (~also in README):

* Load the page
* Should see four tabs all called `"example"`, the right-most should have focus
* Close the second tab
* Close the (now) middle tab
* See two tabs with a gap in the middle and an error in the console

**Comment by liam-goodacre-hpe** [comment]
In my real project I've also seen the whole tab bar disappear and a slightly different error in the console.  However I haven't been able to produce a minimal reproduction of that yet.  So I'm hoping they are the same issue 😃

**Comment by markbrocato** [comment]
I was able to replicate the bug when using Ext 6.2.0, but upgrading to 6.2.1 fixed it.  What version of Ext JS are you using?

**Comment by liam-goodacre-hpe** [comment]
I'm using 6.2.1. The contents of `ext/version.properties` is:

```
#Mon, 21 Nov 2016 17:27:33 -0800
build.number=167
version.major=6
version.minor=2
version.patch=1
version.build=167
version.full=6.2.1.167
build.version=6.2.1.167
ext.version.number=6.2.1.167
version.release=6.2.1

git.current.hash=4e11e443430d912fe6aaaf0df0fec017fe04740c
```

**Comment by liam-goodacre-hpe** [comment]
The date is interesting, because on the sencha support site it says "6.2.1 November 22, 2016".  I'll try redownloading Ext and seeing what happens.

**Comment by markbrocato** [comment]
Actually, I can still reproduce it in 6.2.1.  I didn't realize I had modified your example slightly during debugging.  I think having a numeric itemId is causing the issue, though... another few minutes and I should have it nailed down.

**Comment by markbrocato** [comment]
Yep, that was it.  Sent a PR that shows how to fix the issue:

https://github.com/liam-goodacre-hpe/extjs-reactor-tab-bug/pull/1
