### ISSUE TITLE
Unable to login in npm sencha registry, and https://www.sencha.com/extreact not found

### ISSUE THREAD

**Issue by abenhamdine** [sencha/extjs-reactor#196]
## Expected Behavior

Install scoped @ext packages normally.

## Current Behavior

I tried to login to npm sencha registry with my support portal credentials, but it's impossible because my id is a email adress with an arobase and npm login doesn't seem to support it.

Then I tried to browse https://www.sencha.com/extreact but it's a 404.

As a result, while I'm not login, npm install errors with :  
npm ERR! 404 Not found : @extjs/ext-react

So how to test ext-reactor ?

## Your Environment

Windows 10
Exjs 6.5
npm 4.2.0

**Comment by markbrocato** [comment]
There are some things in motion that aren't quite ready yet.  In the meantime, you can use the classic-boilerplate with a local copy of the Ext JS SDK by following the instructions here: https://github.com/sencha/extjs-reactor/tree/master/packages/reactor-classic-boilerplate

**Comment by abenhamdine** [comment]
Thx for your quick response !
But I ran into some troubles : 
```bash
npm ERR! notarget No compatible version found: @extjs/reactor@^1.0.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.0, 0.1.1, 0.1.2, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.12, 0.1.13, 0.2.0, 0.2.2, 0.2.3, 0.2.5, 0.2.8, 0.2.9, 0.2.10, 0.2.13, 0.2.                                     14, 0.2.15, 0.2.16

npm ERR! notarget No compatible version found: @extjs/reactor-babel-plugin@^1.0.0
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.13, 0.2.0, 0.2.9
```

I had to change the ranges to ^0 to be able to install theses dependencies.
After that, the build succeed, but when I browse http://localhost:8081/, I have the following error : 
```bash
index.js:14 Uncaught TypeError: __webpack_require__.i(...) is not a function
    at eval (index.js:14)
    at Object.<anonymous> (bundle.js?56f0957…:2147)
    at __webpack_require__ (bundle.js?56f0957…:658)
    at fn (bundle.js?56f0957…:86)
    at eval (client:3)
    at Object.<anonymous> (bundle.js?56f0957…:4226)
    at __webpack_require__ (bundle.js?56f0957…:658)
    at bundle.js?56f0957…:707
    at bundle.js?56f0957…:710
```

**Comment by markbrocato** [comment]
For now you should be able to fix that by switching to the v0.2.18 tag:

```
git checkout v0.2.18
cd packages/reactor-classic-boilerplate
npm install
```
1.0.0 versions will be out soon.

**Comment by mpidev** [comment]
Having 404 when npm install
 
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code E404

npm ERR! 404 Not found : @extjs/ext-react
npm ERR! 404 
npm ERR! 404  '@extjs/ext-react' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@extjs/reactor-kitchensink'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by markbrocato** [comment]
@mpidev Did you check out the v0.2.18 tag?

**Comment by abenhamdine** [comment]
Hmm only v0.2.17 succeed for  me, v0.2.18 failed because  @extjs/reactor-webpack-plugin 0.2.18 does not exist.

**Comment by markbrocato** [comment]
Looks like v0.2.18 never got published.  It's published now.

**Comment by abenhamdine** [comment]
Thx Mark, v0.2.18 works now for classic boilerplate

FWIW, tag v0.2.17 and v0.2.18 failed for packages/reactor-material-ui-boilerplate : 

```bash
$ npm start

> @extjs/reactor-material-ui-boilerplate@0.2.18 start C:\node-projects\extjs-reactor\packages\reactor-material-ui-boilerplate
> webpack-dev-server --progress --colors

 10% building modules 1/1 modules 0 active
Project is running at http://localhost:8082/
webpack output is served from /
Content not from webpack is served from ./build
404s will fallback to /index.html                                                                                      94% asset optimization                   building Ext JS bundle: ext => C:\node-projects\extjs-reactor\packages\reactor-material-ui-boilerplate\build\extjs
Sencha Cmd v6.5.0.180
[INF] Loading compiler context
[ERR] Cannot satisfy requirements for "modern"!
[ERR]    The following versions cannot be satisfied:
[ERR]       null: modern (No matches!)
[ERR]
[ERR] BUILD FAILED
[ERR] com.sencha.exceptions.BasicException: com.sencha.exceptions.ExVersion: Cannot resolve package requirements
[ERR]
[ERR] Total time: 0 seconds
[ERR] com.sencha.exceptions.BasicException: com.sencha.exceptions.ExVersion: Cannot resolve package requirements
Error: Error building Ext JS bundle
    at C:\node-projects\extjs-reactor\packages\reactor-material-ui-boilerplate\node_modules\@extjs\reactor-webpack-plugin\dist\index.js:209:65
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by markbrocato** [comment]
Did you link/copy the Ext JS SDK to packages/reactor-material-ui-boilerplate/ext?

**Comment by abenhamdine** [comment]
arrghh no sorry 😭  
Thx a lot, it works now after having created the symlink : 

![image](https://cloud.githubusercontent.com/assets/7466144/26062474/2c8e042a-398b-11e7-9d75-c0d4bef67c40.png)

**Comment by mpidev** [comment]
git checkout v0.2.18
is not working with ext-6.5.0 (grids are empty)
but working with ext-6.2.1

Let's us know when 1.0.0  will be ready.
Thank you.

**Comment by markbrocato** [comment]
@mpidev 1.0.0 is now available.  Please note that the reactor-boilerplate project now targets a new product, [ExtReact](https://www.sencha.com/products/extreact/#app), which is built specifically for React developers without a background in Ext JS.  Ext JS developers should use [reactor-classic-boilerplate](https://github.com/sencha/extjs-reactor/tree/master/packages/reactor-classic-boilerplate) or [reactor-modern-boilerplate](https://github.com/sencha/extjs-reactor/tree/master/packages/reactor-modern-boilerplate) to get up and running.  Both support Ext JS 6.5.

**Comment by abenhamdine** [comment]
Thx for the update.
I close this issue since 1.0.0 is released.

**Comment by lingpri** [comment]
I'm facing the same issue. I have the extjs standard license, but I'm unable to login into npm registry. Please advice
npm login --registry=http://npm.sencha.com --scope=@extjs
username:myemailaddress
>>throws error

**Comment by markbrocato** [comment]
@lingpri Only customers who purchase an ExtReact license have access to the npm registry.  

Ext JS customers can download Ext JS from [the Sencha support portal](https://support.sencha.com).  You can use Ext JS in a React application using the instructions here: https://github.com/sencha/extjs-reactor#building

Also, the extjs-reactor monorepo contains two boilerplates for using Ext JS with React:

[React + Ext JS Classic Boilerplate](https://github.com/sencha/extjs-reactor/tree/master/packages/reactor-classic-boilerplate)

[React + Ext JS Modern Boilerplate](https://github.com/sencha/extjs-reactor/tree/master/packages/reactor-modern-boilerplate)
