### ISSUE TITLE
creating reactor-typescript-boilerplate

### ISSUE THREAD

**Issue by unional** [sencha/extjs-reactor#20]
This is want I'll be doing so I might as well creating a boilerplate and add it here.

Would that be ok for you?

**Comment by markbrocato** [comment]
Yes, that would be great.  Send me a PR when you're ready and I will review.

**Comment by unional** [comment]
Can you give me some pointers on what's need to be done?

For 2.0, as the consumer gets the ExtJS component through `reactify()`, can the `reactor` module keep a list of Ext components used by the app and expose it?

I briefly go through your `reactor-webpack-plugin`, it seems like that's what the `extractFromJSX.js` does. So it is no longer needed?

If we opt for pure ES6 syntax, then is it true that there will be no need to scan for `Ext.create()` and `Ext.require()`?

**Comment by markbrocato** [comment]
You'll still need Ext.require and/or Ext.create for things like grid plugins and non component classes like Ext.data.Store. The webpack plugin scans for those calls so it can forward the dependencies to sencha cmd for tree shaking.

**Comment by unional** [comment]
It sounds like I need to write a jspm-plugin for it.

**Comment by unional** [comment]
Seems like there is a lot of work involved and the jspm edge is disappearing, I'm going to create a typescript boilerplate that uses webpack for now.

**Comment by unional** [comment]
Created https://github.com/unional/reactor-typescript-boilerplate and https://github.com/unional/reactor-webpack-ts-plugin
