### ISSUE TITLE
Docs: using with Redux

### ISSUE THREAD

**Issue by niallobrien** [sencha/extjs-reactor#205]
Hi, I'm just wondering if it would be possible to provide some docs in terms of managing ExtJS component state with Redux?

Thanks in advance.

**Comment by markbrocato** [comment]
For the most part you would use redux as you would with any other react component.  I've written a guide that specifically addresses using Ext stores with redux here:

http://docs.sencha.com/extreact/6.5.0/guides/extreact_stores_in_flux.html

Also, the ExtReact Conference app uses redux:

https://github.com/sencha/extjs-reactor/tree/master/packages/reactor-conference-app

As does this example in kitchensink:

https://examples.sencha.com/ExtReact/6.5.0/kitchensink/#/grids/redux_grid
