### ISSUE TITLE
gitter/slack and 0.2

### ISSUE THREAD

**Issue by unional** [sencha/extjs-reactor#21]
Do extjs has a gitter room or slack room? It would be easier to discuss things there.

Also, will you merge 0.2 to master? Seems like you released 0.2 from that branch.

**Comment by unional** [comment]
> Also, will you merge 0.2 to master

Currently, the boilerplates in 0.2 branch and master branch are broken because `lerna` does not know to update dependencies on that branch.
It updated master branch's boilerplates dependencies to 0.2 while it is still using 0.1 code.

Any CI integration?

**Comment by markbrocato** [comment]
Everything from the 0.2 branch has been merged down to master and I've deleted the 0.2 branch.  You might need to run `lerna bootstrap` to fix the dependency issue.

**Comment by markbrocato** [comment]
Added gitter: https://gitter.im/sencha/extjs-reactor
