### ISSUE TITLE
Rendering Grid component with DIV

### ISSUE THREAD

**Issue by mpidev** [sencha/extjs-reactor#211]
### File Home.js
Just tried to add DIV before and after Grid  and grid is not showing rows anymore
```
render() {
return (
   <div>
   <Grid store={this.store}>
              ...
   </Grid>
  </div>
  )
}
```

was working just fine on previous version 6.2
based on React should works (https://facebook.github.io/react/docs/rendering-elements.html)

**Comment by markbrocato** [comment]
Grid needs to either get an explicit height and width...

```jsx
<div>
  <Grid height={500} width={600} />
</div>
```

...or be sized by the parent container, for example a container with layout="fit":

```jsx
<Container layout="fit">
  <Grid/>
</Container>
```
