### ISSUE TITLE
Simplify reactify(target)

### ISSUE THREAD

**Issue by unional** [sencha/extjs-reactor#26]
From https://github.com/sencha/extjs-reactor/issues/12#issuecomment-264384809

I don't like `reactify(...targets)`. I would suggest to keep it simple and do `reactify(target)`.

The consumer does not gain much from doing this "shortcut". It is better to keep it simple. Also, `reactify(...targets)` makes it hard to type and use in TypeScript in the future,when `react` `Property` and `State` can pass down to ExtJS component. 
It also makes the code impossible to use generics.

```ts
import React = require('react')  // You should do this too, CommonJS <-> ESM interop is flawed.
import { reactify } from '@extjs/reactor'

interface GridProperty {}
interface GridState {}
interface GridInterface { }
interface PanelProperty {}
interface PanelState {}
interface PanelInterface { }

const Grid1 = reactify('grid') as GridInterface & React.Component<GridProperty, GridState>

const [ Grid2, Panel ] = reactify('grid', 'panel') as [
  GridInterface & React.Component<GridProperty, GridState>,
  PanelInterface & React.Component<PanelProperty, PanelState>
]

// If using generic, which is what I'm doing:
const Grid3 = reactify<GridInterface, GridProperty, GridState>('grid')
```

I'm using Intersection type `GridInterface & React.Component<...>` because this would allow the consumer to extend the default grid and provide their own property and state.

**Comment by markbrocato** [comment]
See my comment from the other thread:

You don't have to specify multiple parameters to reactify.  For example

```javascript
const [Grid, Panel] = reactify('grid', 'panel');
```

could be rewritten as 

```javascript
const Grid = reactify('grid');
const Panel = reactify('panel');
```

Maybe the typescript definition should restrict this to a single argument?  I personally find the syntax to reactify multiple components convenient and more in line with how we use ES6 to import multiple components:

`import { Grid, Panel } from '@extjs/reactor/modern`

**Comment by unional** [comment]
The issue with `reactify(...targets)` is that the return value is complex. It is not like `foo(...args): string[]`. Each return value in the array has its own type and structure. It is not good to mix them together.

When typing this function, typically the best way is to use generics:

```ts
function reactify<Class, Props, State>(target: string | Function): Class & React.Component<Props, State>;
```

For `reactify(...targets)`, it is cumbersome:

```ts
// Overloading way
function reactify<Class1, Props1, State1>(target: string | Function): Class1 & React.Component<Props1, State1>;
function reactify<Class1, Props1, State1, Class2, Props2, State2>(target1: string | Function, target2: string | Function): [Class1 & React.Component<Props1, State1>, Class2 & React.Component<Props2, State2>];
// and so on...

// or spread, but we can't specify the return type as it depends on number on entries and type of each entry.
function reactify(...targets: (string | Function)[]): (???, React.Component<???, ???>];
```

**Comment by unional** [comment]
So it will ends up with `any`:
```ts
function reactify(...targets: (string | Function)[]): any;
```

**Comment by markbrocato** [comment]
I'm not that familiar with TypeScript, does it not allow you to overload functions? So:

```TypeScript
function reactify(target: (string | Function)): React.Component;
function reactify(...targets: (string | Function)[]): React.Component[];
```

**Comment by markbrocato** [comment]
Seems like that kind of a thing would be necessary in a strongly typed language.

**Comment by unional** [comment]
Yes, it can overload. However, it's about the generic type of the class, props, and state.

`React.Component` is a generic class expecting `<P, S>`. To use it, I need to specify what should we expect for those generic types, e.g.:

```ts
const MyComp: = new React.Component<{ foo: string}, { boo: bolean }>();

function reactify(target: (string | Function)): React.Component<any, any>;
// this allow consumer to specify their own props and state.
function reactify<P, S>(target: (string | Function)): React.Component<P, S>;
```

**Comment by unional** [comment]
I can see your use case. Will just do overload to work with the common use case and support `any` for the spread case.
