### ISSUE TITLE
Support of Ext.widget

### ISSUE THREAD

**Issue by psartini** [sencha/extjs-reactor#29]
I tried to use a TreeList inside of a Container:
```javascript
<Container ......>
	<TreeList ..... />
</Container>
```
This results is the following error message:
> Uncaught Error: Could not render child item: [object Object]

After looking at the code, it got clear that reactor does not support rendering of any Ext.widget right now.
https://github.com/sencha/extjs-reactor/blob/master/packages/reactor/src/ExtJSComponent.js#L175

Not sure about the implications, but I tried this:
```javascript
if (item instanceof Ext.Component
    || item instanceof Ext.Widget) {
	(item.dock ? dockedItems : items).push(item);
```

My TreeList does now render and seems to work.
Will there be any problems with this?

**Comment by markbrocato** [comment]
Good catch!  There are a few other places where `instanceof Ext.Component` appear.  I'll change them to `Ext.Base` in the next update.

**Comment by markbrocato** [comment]
Should be fixed now on master.
