### ISSUE TITLE
ReactDOM private methods

### ISSUE THREAD

**Issue by jsheely** [sencha/extjs-reactor#291]
Reactor uses ReactDOM private methods that have now been made fully private / internal as of React 16.  Any imports to react-dom/lib will not work in React 16

Example:
https://github.com/sencha/extjs-reactor/blob/master/packages/reactor/src/ExtJSComponent.js#L2

We will need to update the ExtJSComponent in order to utilize the latest version of React

**Comment by markbrocato** [comment]
We've been watching the development of React 16 closely.  I've filed an issue with the React team to track this: https://github.com/facebook/react/issues/9192

You can see from the conversation there that React 16 will, for the first time, officially support third-party renderers.  That capability just isn't present yet in the beta, but they've assured us that it will be by the time it's released.

**Comment by jsheely** [comment]
Excellent. Thanks for the update

**Comment by matthew-gordon-hp** [comment]
Hi Mark, any update on this now React 16 is released?

**Comment by BugiDev** [comment]
Hello @markbrocato 
Are there any news for React 16 support? :)

**Comment by jsheely** [comment]
I don't think @markbrocato works for Sencha anymore. We need a new team leader on this project to let us know the status of the project

@dbuhrman Are you able to shed any light on the status of the project?
