### ISSUE TITLE
Safari doesn't support reactor-kitchensink.

### ISSUE THREAD

**Issue by YacheLee** [sencha/extjs-reactor#312]
I can't see any content of reactor-kitchensink in  Safari.
But it does work properly in [http://examples.sencha.com/ExtReact/6.5.1/kitchensink](http://examples.sencha.com/ExtReact/6.5.1/kitchensink)
How to do the magic?

**Comment by mgusmano** [comment]
I was able to see it with safari - can you provide more details?
![screen shot 2018-03-08 at 8 49 11 am](https://user-images.githubusercontent.com/2080140/37154333-a60338fa-22ad-11e8-8469-e8744e3433d6.png)

**Comment by mgusmano** [comment]
i am closing this issue, if you have a use case that shows safari not working, please open up a new issue
