### ISSUE TITLE
Charts React 16 kitchensink Issues

### ISSUE THREAD

**Issue by psamal89** [sencha/extjs-reactor#363]
1. Area
  a)  Stacked,Full stacked,Negative value area charts theme button missing and Basic area chart  theme button as well as refresh button are missing.

2.Bar
  a) Basic bar,full stacked bar  theme and stacked bar theme as well as refresh button missing

3. Boxplot charts theme button missing.

4. Column
  a) Basic column chart theme and refresh buttons missing.
  b) Stacked column chart theme,refresh,stack,zoom,group and pan buttons are missing.
  c) Column_with_renderer column chart refresh button missing.
  d) Multiaxis_column  chart not loading throws console error.

5. 3D column
  a) In Basic_3d_column chart theme and refresh buttons are missing.
  b) 3d_grouped column chart not loading throws console error.
  c) 3d_stacked column charts legends not working and theme,stack and group buttons are missing.
  d) Negative_values column chart page not loading throws console error.
  e) 3d_column_with_renderer column chart not loading throws console error.

6. Financial
  a) Candlestick and ohlc financial chart not loading throws console error.

7.Gauges
  a) Basic_gauge refresh button missing.

8. Line
  a) In basic_line theme button missing.
  b) In basic_markers theme and refresh button missing.
  c) In Spline theme button missing.
  d) In spline_markers theme button missing.
  e) In plot theme,refresh.pan and zoom labels are missing.
  f) In with_renderer theme and refresh labels are missing.
  g)In real time line charts throws this error " Uncaught TypeError: chart.getAxes is not a function"

9. Navigator chart -- theme,pan and zoom labels are missing.
10. Pie
  a) In basic_pie and 3d pie theme and refresh labels are missing.
  b) In spie,donut and double donut theme button missing.
11. Radar
  a) In basic_radar and marked theme button missing.
  b) In filled  theme and refresh button are missing.
  c) multiaxis page not loading throws console error.
12.Scatter
  a) In basic_scatter theme,refresh,pan and zoom labels are missing.
  b) In custom_icons and Bubble, theme and refresh labels are missing.

**Comment by simran-git** [comment]
1) Area
a) Stacked,Full stacked,Negative value area charts theme button missing and Basic area chart theme button as well as refresh button are missing.
 - FIXED
2.Bar
a) Basic bar,full stacked bar theme and stacked bar theme as well as refresh button missing
- FIXED

3) Boxplot charts theme button missing.
 - FIXED

4) Column
a) Basic column chart theme and refresh buttons missing.
- FIXED
b) Stacked column chart theme,refresh,stack,zoom,group and pan buttons are missing.
- FIXED
c) Column_with_renderer column chart refresh button missing.
- FIXED
d) Multiaxis_column chart not loading throws console error.
- OPEN

5) 3D column
a) In Basic_3d_column chart theme and refresh buttons are missing.
- FIXED
b) 3d_grouped column chart not loading throws console error.
- OPEN (Gets fixed on loading twice)
c) 3d_stacked column charts legends not working and theme,stack and group buttons are missing.
- FIXED
d) Negative_values column chart page not loading throws console error.
- OPEN (Gets fixed on loading twice)
e) 3d_column_with_renderer column chart not loading throws console error.
- OPEN (Gets fixed on loading twice)


6) Financial
a) Candlestick and ohlc financial chart not loading throws console error.
- OPEN

7.Gauges
a) Basic_gauge refresh button missing.
- FIXED

8) Line
a) In basic_line theme button missing.
- FIXED

b) In basic_markers theme and refresh button missing.
- FIXED
c) In Spline theme button missing.
- FIXED
d) In spline_markers theme button missing.
- FIXED
e) In plot theme,refresh.pan and zoom labels are missing.
- FIXED
f) In with_renderer theme and refresh labels are missing.
- FIXED
g)In real time line charts throws this error " Uncaught TypeError: chart.getAxes is not a function"
- FIXED

Navigator chart -- theme,pan and zoom labels are missing.
- FIXED

10) Pie
a) In basic_pie and 3d pie theme and refresh labels are missing.
- FIXED
b) In spie,donut and double donut theme button missing.
- FIXED

11)Radar
a) In basic_radar and marked theme button missing.
- FIXED
b) In filled theme and refresh button are missing.
- FIXED
c) multiaxis page not loading throws console error.
- OPEN (Gets fixed on loading twice)
12.Scatter
a) In basic_scatter theme,refresh,pan and zoom labels are missing.
- FIXED
b) In custom_icons and Bubble, theme and refresh labels are missing.
- FIXED

**Comment by simran-git** [comment]
CHARTS EXISTING OPEN ISSUES

1) Across all charts - PAN/ZOOM STACKED/GROUP segmented buttons not changing state. Not clear on Pan/Zoom functionality as well
2) Theme - Menu items not aligned properly
3) Column->Multiaxis_column chart, 3d -> 3d_column_with_renderer,Negative_values, Radar -> multiaxis
     page not loading first time. Gets fixed second time.
4) Financial->Candlestick and ohlc financial chart not loading throws console error
