### ISSUE TITLE
Is React able to eliminate the Ext JS MVVM pattern?

### ISSUE THREAD

**Issue by AjaxSolutions** [sencha/extjs-reactor#37]
I understand how React and Redux/MobX work together.

Question: does the extjs-reactor entirely eliminate the need to use Ext JS view models and view controllers?

**Comment by markbrocato** [comment]
In short, yes.

You would still be able to use them, but in most cases they would be redundant to something like redux.  The extjs-reactor package allows you to use Ext JS purely as a component library, minus the frameworky bits.
