### ISSUE TITLE
React 16| Text position issue

### ISSUE THREAD

**Issue by simran-git** [sencha/extjs-reactor#376]
Text is being rendered after component

For eg : 
```
<Toolbar>
Some Text
<Button>
</Button>
</Toolbar>
```

In this case, button is positioned left of text whereas it should be right of text.

Seen in Draw examples in Kitchen Sink

**Comment by mgusmano** [comment]
any div's need a Container parent element - see Draw.js

            <Panel shadow layout="fit">
                <Toolbar docked="top">
--- >             <Container>
                      <div style={{fontSize: Ext.os.is.Phone ? '12px' : '14px'}}>Use your {Ext.supports.Touch ? 'finger' : 'mouse'} to paint on the surface below.</div>
--- >                    </Container>
                    <Spacer/>
                    <Button handler={this.clear} text="Clear"/>
                </Toolbar>
                <Draw ref="draw"/>  
            </Panel>

**Comment by simran-git** [comment]
Its still not rendered at correct position in Draw example
