### ISSUE TITLE
Props with true value

### ISSUE THREAD

**Issue by AjaxSolutions** [sencha/extjs-reactor#43]
Do I need to specify `shadow={true}`?

Value true should be optional(?).

` <Panel title="Employees" layout="fit" flex={1} margin="20" shadow={true}>`

In this example, the exactly prop is not followed by true.

```
<Match
  pattern="/messages/:userId"
  component={ExampleComponent}
  exactly
/>
```

**Comment by markbrocato** [comment]
You are correct, true is not needed in this case.  I will update the boilerplate.

**Comment by markbrocato** [comment]
Actually, upon further review, it looks like omitting the value results in a parsing error in the reactor-webpack-plugin.  Apparently acorn-jsx doesn't like it.  Looking into this further...

**Comment by markbrocato** [comment]
This should now be fixed.  I switched the parser for the webpack plugin from acorn to babylon.
