### ISSUE TITLE
getting error when i start server 

### ISSUE THREAD

**Issue by akhillgopinath** [sencha/extjs-reactor#5]
here is the error 

Sencha Cmd v6.0.2.14
[ERR] 
[ERR] BUILD FAILED
[ERR] com.sencha.exceptions.BasicException: java.lang.NullPointerException
[ERR] 
[ERR] Total time: 0 seconds
[ERR] com.sencha.exceptions.BasicException: java.lang.NullPointerException

**Comment by dongryphon** [comment]
I'd try upgrading to latest GA of Cmd which is `6.2.0` as I believe there were some enhancements made for this build process

**Comment by markbrocato** [comment]
Are you using the boilerplate?  

https://github.com/sencha/extjs-reactor/tree/master/packages/reactor-boilerplate

If so, did you copy the Ext JS SDK to packages/reactor-boilerplate/ext as mentioned in the readme?

**Comment by markbrocato** [comment]
Add `--port 3030` to the end of the npm start script in package.json:

https://github.com/sencha/extjs-reactor/blob/master/packages/reactor-boilerplate/package.json#L8
