### ISSUE TITLE
Classic example App.js

### ISSUE THREAD

**Issue by AjaxSolutions** [sencha/extjs-reactor#50]
Can the classic App.js example be modified as shown below?  I removed the enclosing panel.

```
...
export default class App extends Component {
    ...
    render() {
        const { person } = this.state;
        
        return (
            <Grid
                store={this.store}
                title="Employees"
                columns={[
                    { text: 'Name', dataIndex: 'name', flex: 1 },
                    { text: 'Email', dataIndex: 'email', flex: 1 }
                ]}
                onRowClick={(grid, record) => this.onRowClick(record.data)}
            >
                { person && (
                    <Person
                        person={person}
                        onSave={person => this.onSavePerson(person)}
                        onClose={() => this.setState({ person: null })}
                    />
                ) }
                <Toolbar dock="top">
                    <TextField emptyText="Search" onChange={(field, value) => this.onSearch(value)} flex={1}/>
                </Toolbar>
            </Grid>
        );
    }
}
```
There is something wrong with the child/parent relationship(?)

Evaluate the following in the console.

The grid has only one child, but the toolbar and the window list the grid as the ownerCt.

Why is the window a child of the grid as opposed to being rendered to Ext.getBody()?

```
Ext.first('grid').items.first().xtype
"tableview"
Ext.first('window').ownerCt
constructor {ownerGrid: constructor, actionables: Array[0], initialConfig: Object, id: "gridpanel-1003", autoGenId: true…}
Ext.first('toolbar').ownerCt     
constructor {ownerGrid: constructor, actionables: Array[0], initialConfig: Object, id: "gridpanel-1003", autoGenId: true…}
Ext.first('grid').items.length
1
```

**Comment by markbrocato** [comment]
Yes, that modification should be fine.  In this case the Window is a child of the Grid because it appears in the Grid's props.children.  Making a window a child of other component is also common in pure Ext JS when it is desirable for the window to be bound to the same viewmodel as the parent component.  The parent/child relationship shouldn't affect rendering.

**Comment by AjaxSolutions** [comment]
I still think there's something wrong with the parent/child relationship in Ext JS, not React.

The grid.items.length is not correct.  The value is (1), but more than one Ext JS component claims the grid as ownerCt.

**Comment by markbrocato** [comment]
The toolbar is in the dockedItems collection.  Only the window is in the items collection in this case.

**Comment by AjaxSolutions** [comment]
Click the grid row to open the Person window and inspect the number of items on the grid.  The number should increase by one since the Person window is now a child of the grid.  I don't see that when the Person window is displayed the number of grid items is increased.

**Comment by AjaxSolutions** [comment]
> Making a window a child of other component is also common in pure Ext JS when it is desirable for the window to be bound to the same viewmodel as the parent component. 

This is very interesting and I didn't know that. Evaluate this code in the console before and after opening the window.  I don't see that the number of panel's items is increasing.

`Ext.first('panel[title="Employees"]').items.length // 1`

**Comment by AjaxSolutions** [comment]
Thank you!
