### ISSUE TITLE
Documentation suggestion

### ISSUE THREAD

**Issue by AjaxSolutions** [sencha/extjs-reactor#51]
It took me some time to realize that the text "Hello World!" in the top example is converted to an Ext JS component which becomes a child of the Panel.  Actually, any div element under Panel is converted to a separate Ext JS component.

The bottom example does not result in new children being added to the Panel.  I don't see that this is documented.
```
<Panel title="React Ext JS">
    Hello World!
</Panel>
```

`<Panel title="React Ext JS" html="Hello World!" />`

**Comment by AjaxSolutions** [comment]
For example, these two divs under Panel add two Ext JS child components to Panel.
```
<Panel
    title={employee.name}
    ...
>
    <div style={{padding: '0 0 30px 0'}}>
        <div style={{float:'left', ...fontStyles}}>{employee.email}</div>
        <div style={{float:'right', ...fontStyles}}>{employee.phone}</div>
    </div>

    <div style={{
        textAlign: 'center',
        color: '#606060',
        fontWeight: 100,
        ...fontStyles
        }}>Vacation Balance</div>
    ...
</Panel>
```

These two divs enclosed in another div add one child Ext JS component to the Panel.
```
<Panel
    title={employee.name}
    ...
>
    <div>
        <div style={{padding: '0 0 30px 0'}}>
            <div style={{float:'left', ...fontStyles}}>{employee.email}</div>
            <div style={{float:'right', ...fontStyles}}>{employee.phone}</div>
        </div>

        <div style={{
            textAlign: 'center',
            color: '#606060',
            fontWeight: 100,
            ...fontStyles
            }}>Vacation Balance</div>
    </div>
    ...
</Panel>
```

**Comment by markbrocato** [comment]
I think the implementation of reactor can be improved here.  I think having only text content should result in setting the html prop, and having multiple children should only result in one child component.  I should be able to make those changes next week.

**Comment by markbrocato** [comment]
Thank you for pointing this out!

**Comment by markbrocato** [comment]
I've added a section to the docs here: https://github.com/sencha/extjs-reactor#using-html-elements-and-non-ext-js-components-inside-of-ext-js-components

I've also made it so that if a component only has text content, that content is passed to the html config of the generated Ext JS component, preventing the creation of an additional nested component.
