### ISSUE TITLE
Panel documentation issue

### ISSUE THREAD

**Issue by AjaxSolutions** [sencha/extjs-reactor#56]
I just tried the latest code ("@extjs/reactor@^0.2.9"), and the following two configurations are not equivalent.

```
<Panel>Hello World!</Panel>

<Panel html="Hello World!"></Panel>
```

The documentation states: "When an Ext JS component contains only text, that text will be set as the html config of the component."

I see a new child component being added to the Panel, and the child (not the Panel) contains the text Hello World!

I don't have a problem with how the feature currently works, but the doc is not correct.

**Comment by markbrocato** [comment]
That change has been committed to master but we haven't yet published a new version to npm.  That should be coming in the next few days along with a few other fixes.
