### ISSUE TITLE
Panel won't render a child passed as a function

### ISSUE THREAD

**Issue by AjaxSolutions** [sencha/extjs-reactor#59]
The First! child should be rendered, but it's ignored.

https://mxstbr.blog/2017/02/react-children-deepdive/#child-components
```
export default class Employee extends Component {
    ...
    render () {
        ...
        return (
            <Panel
            ...
            >
                {() => <h1>First!</h1>}
               
                Second!

                <div style={{padding: '0 0 30px 0'}}>
                         ....
                </div>                
                ...
            </Panel>
        )
    }
}
```

**Comment by markbrocato** [comment]
While it is possible to evaluate props.children as a function in your own components, it is my understanding that this is not a common practice in React.  For example, the following won't render anything:

`<div>{() => "Foo"}</div>`
