### ISSUE TITLE
Ext.onReady is not a function

### ISSUE THREAD

**Issue by frankbolviken** [sencha/extjs-reactor#6]
Hi,

I have been trying to integrate this in my existing app. Launching the boilerplace works fine.
But when I copy over the different settings from the boilerplate, I get this error when I try to view the page.

`index.jsx:24 Uncaught TypeError: Ext.onReady is not a function(…)`

When i inspect the Ext object in the console, I get this:

`Ext
Object {platformTags: Object, Boot: Object}`

So it seems like Ext is not initialized properly, but I'm not understand what settings I am missing.
Any pointers?

**Comment by markbrocato** [comment]
Have you added a script tag to import ext.js as done here? https://github.com/sencha/extjs-reactor/blob/master/packages/reactor-boilerplate/static/index.html#L14

Have you added the ExtJSReactorWebpackPlugin to your webpack config as done here? https://github.com/sencha/extjs-reactor/blob/master/packages/reactor-boilerplate/webpack.config.dev.js#L30

Can you post the console output of your webpack build and the build config itself?

**Comment by frankbolviken** [comment]
Yes I have done as you described.

What I found is that when i removed all Extjs references (Ext.require and <x-??> from the render methods, I got the same in the boilerplate. SO it seems that if you are not using any extjs components, it failes to load because Ext.onReady is undefined.

**Comment by frankbolviken** [comment]
I got a bit further, but now I get this error when trying to use a grid for instance:
<img width="848" alt="screen shot 2016-11-14 at 15 27 16" src="https://cloud.githubusercontent.com/assets/688190/20268320/ec0c3c96-aa7e-11e6-9cfd-7ac00dd313f4.png">

**Comment by markbrocato** [comment]
Would you pausing on that "c is not a constructor" error and seeing which class or alias it's trying to load using the chrome debugger?

**Comment by frankbolviken** [comment]
![screen shot 2016-11-14 at 15 34 51](https://cloud.githubusercontent.com/assets/688190/20268547/eb881280-aa7f-11e6-983b-2adbe6b5498b.png)

it fails to load /widget/grid.js above.. I suspect that it's something regarding this? (See previously added image)

**Comment by markbrocato** [comment]
Would you mine posting your webpack config and the contents of build/ext/manifest.js?

**Comment by frankbolviken** [comment]
If you try to remove the references to ExtJS components in the boilerplate files, you will see that if you try to visit the running app, you will get a Ext.onReady us undefined error. That's issue 1.

**Comment by markbrocato** [comment]
^ I'll put in a safeguard for that.  Should be easy.

**Comment by frankbolviken** [comment]
`"use strict";
var webpack = require('webpack');
var path = require('path');
var loaders = require('./webpack.loaders');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtJSReactorWebpackPlugin = require('@extjs/reactor-webpack-plugin');

const HOST = process.env.HOST || "127.0.0.1";
const PORT = process.env.PORT || "8888";

// global css
loaders.push({
	test: /[\/\\](node_modules|global)[\/\\].*\.css$/,
	loaders: [
		'style?sourceMap',
		'css'
	]
});
// local scss modules
loaders.push({
	test: /[\/\\]src[\/\\].*\.scss/,
	exclude: /(node_modules|bower_components|public)/,
	loaders: [
		'style?sourceMap',
		'css?modules&importLoaders=1&localIdentName=[local]',
		'sass'
	]
});

// local css modules
loaders.push({
	test: /[\/\\]src[\/\\].*\.css/,
	exclude: /(node_modules|bower_components|public)/,
	loaders: [
		'style?sourceMap',
		'css?modules&importLoaders=1&localIdentName=[local]'
	]
});

module.exports = {
	entry: [
		`webpack-dev-server/client?http://${HOST}:${PORT}`,
		`webpack/hot/only-dev-server`,
		`./src/index.jsx` // Your appʼs entry point
	],
	devtool: process.env.WEBPACK_DEVTOOL || 'cheap-module-source-map',
	output: {
		path: path.join(__dirname, 'public'),
		publicPath: '/',
		filename: 'bundle.js'
	},
	resolve: {
		extensions: ['', '.js', '.jsx']
	},
	module: {
		loaders
	},
	devServer: {
		contentBase: "./public",
		// do not print bundle build stats
		noInfo: true,
		// enable HMR
		hot: true,
		// embed the webpack-dev-server runtime into the bundle
		inline: true,
		// serve index.html in place of 404 responses to allow HTML5 history
		historyApiFallback: true,
		port: PORT,
		host: HOST
	},
	plugins: [
		new webpack.NoErrorsPlugin(),
		new webpack.HotModuleReplacementPlugin(),
		new HtmlWebpackPlugin({
			template: './src/template.html'
		}),
		new ExtJSReactorWebpackPlugin({
				sdk: 'ext', // you need to copy the Ext JS SDK to the root of this package, or you can specify a full path to some other location
				theme: 'theme-material',
				output: path.join('public', 'ext')
		})
	]
};
`

**Comment by frankbolviken** [comment]
[Archive.zip](https://github.com/sencha/extjs-reactor/files/589612/Archive.zip)

Attached you will find my project setup. (You will need to create the ext folder, I didnt include that in zip as it's to *** huge :P 

I find some very strange behaviours :(

I would really like to get this working as this is exactly what we have been looking for where I work!

**Comment by markbrocato** [comment]
Thank you, that's very helpful.  Looks like initial build is fine, then subsequent builds wind up removing almost all of the classes from ext.js.  It's definitely an issue with the webpack plugin.  In the meantime, you could use ext-modern-all.js, modern/theme-material/resources/theme-material-all.css, and modern/theme-material/theme-material.js in development.  I hope to have this worked out today.

**Comment by markbrocato** [comment]
I've just published a new build of @extjs/reactor-webpack-plugin (v0.1.12) which should fix your issues.  

In diagnosing and fixing the problem I noticed that a rogue sencha cmd process was thrashing my build, which resulted in the ext.js file missing almost all of the classes.  If this happens to you, kill any stray java processes that might be running and try again.

Also, in your Landing.jsx view, you'll need to add a height and width to the <x-grid> element, for example <x-grid height={500} width={700} ... /> or give some size/flex to the parent div, otherwise the grid will be 0x0px.

**Comment by frankbolviken** [comment]
Thanks alot for the quick and helpfull response!  I will investigate.

**Comment by markbrocato** [comment]
@frankbolviken Did 0.1.12 solve your issue?

**Comment by markbrocato** [comment]
Closing this issue.  Will reopen if further problems are reported.
