### ISSUE TITLE
Class properties cause parsing error in reactor-webpack-plugin

### ISSUE THREAD

**Issue by MarkPhillips7** [sencha/extjs-reactor#60]
I'm considering using extjs-reactor and have been trying to get it working with some boilerplate projects like https://github.com/erikras/react-redux-universal-hot-example and https://github.com/reactjs/redux/tree/master/examples/real-world.

In both cases reactor-webpack-plugin reported error messages like
`error parsing [path_to_js]`

It appears as though https://github.com/RReverser/acorn-jsx/issues/36 is the problem.

Problem areas indicated by comments:
```jsx
class MyThing extends Component {
  static propTypes = { // error occurs at the '='
    foo: PropTypes.string.isRequired,
  }
  boundHandler = () => this.isBound(); // this line also causes the error
  render() { return <OtherThing bar={this.props.foo} onClick={this.boundHandler} /> }
}
```

It seems that the static propTypes definition is a fairly common approach. And the second line that causes the error is really nice because then we never need to call `.bind(this)`. I was able to get things working by refactoring the code to conform to stable standards, but I would rather not have to.

I don't really know but it looks like using https://github.com/babel/babylon instead of acorn might be needed to address this.

**Comment by markbrocato** [comment]
Thank you for the suggestion.  I'll look into this early next week and let you know what I find.  I'm certainly not opposed to swapping out the parser if babylon works better.

**Comment by MarkPhillips7** [comment]
Thanks! I can verify that your commit indeed fixed it for me.
