### ISSUE TITLE
Build error: index.html not found

### ISSUE THREAD

**Issue by MoimHossain** [sencha/extjs-reactor#61]
Hi there, I am trying to run ExtJS over React, as our organization is committed to React development. I worked before with ExtJS, so wanted to promote the power of ExtJS in combination to React. But I couldn't make it work yet.

#What I have done so far:
- Downloaded the ExtJS 6 zip and unzipped into a folder "ext" - as suggested in readme.md.
- When I run the build, it gives me the following error message
![image](https://cloud.githubusercontent.com/assets/1510438/22874004/eebb7c18-f1c3-11e6-9ab9-f9c4c39a54cd.png)

The directory structure looks like following:
![image](https://cloud.githubusercontent.com/assets/1510438/22874038/1d47bce0-f1c4-11e6-9231-1c599c760904.png)

Is the a problem addressed before, or I am just doing it wrong?

**Comment by markbrocato** [comment]
Try updating to the latest release of Sencha Cmd, v6.2.1.  I am able to build the boilerplate on that version just fine.

**Comment by petrvecera** [comment]
Upgrade to 6.2.1 resolved the issue http://stackoverflow.com/a/42207350/1768843
