### ISSUE TITLE
BufferedStore Configuration

### ISSUE THREAD

**Issue by BlaineBradbury** [sencha/extjs-reactor#64]
I have tried to follow this example:  http://examples.sencha.com/extjs/6.2.0/examples/classic/grid/filtered-buffered-store.js

ExtJSComponent.js throws errors:
"Could not create Ext JS component with config"
&
"Uncaught TypeError: Cannot read property 'length' of undefined"

      this.store = Ext.create('Ext.data.BufferedStore', {
          id: 'store',
          storeId: 'store',
          model: 'extcomponents.model.mydata',
          pageSize: 21,
          leadingBufferZone: 300,
          proxy: {
              type: 'ajax',
              url: myurl,
              reader: {
                  type: 'json',
                  rootProperty: 'ROWS',
                  totalProperty: 'TOTALCOUNT'
              },
              simpleSortMode: true
          },
          listeners: {
            load: function(){
                console.log('api returned')
            }
          },
          autoLoad: true
      })

If I changed BufferedStore to Store... works fine (though no buffer).

**Comment by markbrocato** [comment]
Seems to be working for me - what does the response from the server look like?

**Comment by BlaineBradbury** [comment]
The error comes before the network call ever happens.  I'm not sure how to debug.  Here is the extended console output:

Could not create Ext JS component with config Object {listeners: Object, title: “MyGrid”, plugins: Array[2], store: constructor, columns: Array[28]…}
mountComponent @ ExtJSComponent.js:122
mountComponent @ ReactReconciler.js:46
mountChildren @ ReactMultiChild.js:238
_createInitialConfig @ ExtJSComponent.js:216
mountComponent @ ExtJSComponent.js:106
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
mountComponentIntoNode @ ReactMount.js:104
perform @ Transaction.js:140
batchedMountComponentIntoNode @ ReactMount.js:126
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
_renderNewRootComponent @ ReactMount.js:320
_renderSubtreeIntoContainer @ ReactMount.js:401
render @ ReactMount.js:422
(anonymous) @ index.js:21
invoke @ ext.js?06e82f5…:19185
doInvokeAll @ ext.js?06e82f5…:19229
invokeAll @ ext.js?06e82f5…:19198
handleReady @ ext.js?06e82f5…:19154
(anonymous) @ ext.js?06e82f5…:19169
(anonymous) @ ext.js?06e82f5…:8034
(anonymous) @ ext.js?06e82f5…:8231
ExtJSComponent.js:123 Uncaught TypeError: Cannot read property 'length' of undefined
    at constructor.hasRange (ext.js?06e82f5…:81897)
    at constructor.rangeCached (ext.js?06e82f5…:82729)
    at constructor.getRange (ext.js?06e82f5…:82276)
    at constructor.deselectAll (ext.js?06e82f5…:87458)
    at constructor.refreshSelection (ext.js?06e82f5…:87705)
    at constructor.updateStore (ext.js?06e82f5…:87441)
    at constructor.updateStore (ext.js?06e82f5…:20785)
    at constructor.callParent (ext.js?06e82f5…:13253)
    at constructor.updateStore (ext.js?06e82f5…:97972)
    at constructor.setter [as setStore] (ext.js?06e82f5…:11543)
hasRange @ ext.js?06e82f5…:81897
rangeCached @ ext.js?06e82f5…:82729
getRange @ ext.js?06e82f5…:82276
deselectAll @ ext.js?06e82f5…:87458
refreshSelection @ ext.js?06e82f5…:87705
updateStore @ ext.js?06e82f5…:87441
(anonymous) @ ext.js?06e82f5…:20785
callParent @ ext.js?06e82f5…:13253
updateStore @ ext.js?06e82f5…:97972
setter @ ext.js?06e82f5…:11543
(anonymous) @ ext.js?06e82f5…:11477
updateGrid @ ext.js?06e82f5…:104702
setter @ ext.js?06e82f5…:11504
init @ ext.js?06e82f5…:104682
applyPlugins @ ext.js?06e82f5…:42605
setter @ ext.js?06e82f5…:11498
configure @ ext.js?06e82f5…:12017
initConfig @ ext.js?06e82f5…:13388
constructor @ ext.js?06e82f5…:21885
constructor @ ext.js?06e82f5…:43015
callParent @ ext.js?06e82f5…:13253
constructor @ ext.js?06e82f5…:44722
callParent @ ext.js?06e82f5…:13253
constructor @ ext.js?06e82f5…:50606
callParent @ ext.js?06e82f5…:13253
constructor @ ext.js?06e82f5…:77009
callParent @ ext.js?06e82f5…:13253
constructor @ ext.js?06e82f5…:95465
constructor @ ext.js?06e82f5…:13846
createExtJSComponent @ index.js:92
mountComponent @ ExtJSComponent.js:116
mountComponent @ ReactReconciler.js:46
mountChildren @ ReactMultiChild.js:238
_createInitialConfig @ ExtJSComponent.js:216
mountComponent @ ExtJSComponent.js:106
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
performInitialMount @ ReactCompositeComponent.js:371
mountComponent @ ReactCompositeComponent.js:258
mountComponent @ ReactReconciler.js:46
mountComponentIntoNode @ ReactMount.js:104
perform @ Transaction.js:140
batchedMountComponentIntoNode @ ReactMount.js:126
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
_renderNewRootComponent @ ReactMount.js:320
_renderSubtreeIntoContainer @ ReactMount.js:401
render @ ReactMount.js:422
(anonymous) @ index.js:21
invoke @ ext.js?06e82f5…:19185
doInvokeAll @ ext.js?06e82f5…:19229
invokeAll @ ext.js?06e82f5…:19198
handleReady @ ext.js?06e82f5…:19154
(anonymous) @ ext.js?06e82f5…:19169
(anonymous) @ ext.js?06e82f5…:8034
(anonymous) @ ext.js?06e82f5…:8231
ext.js?06e82f5…:87716 Uncaught TypeError: Cannot read property 'length' of undefined
    at constructor.onSelectionStoreRemove (ext.js?06e82f5…:87716)
    at constructor.onSelectionStoreClear (ext.js?06e82f5…:87742)
    at constructor.fire (ext.js?06e82f5…:21306)
    at constructor.doFireEvent (ext.js?06e82f5…:22257)
    at constructor.fireEventArgs (ext.js?06e82f5…:22110)
    at constructor.fireEvent (ext.js?06e82f5…:22072)
    at constructor.onPageMapClear (ext.js?06e82f5…:82599)
    at constructor.fire (ext.js?06e82f5…:21306)
    at constructor.doFireEvent (ext.js?06e82f5…:22257)
    at constructor.fireEventArgs (ext.js?06e82f5…:22110)


![image](https://cloud.githubusercontent.com/assets/282549/22901444/b1135d5e-f1ff-11e6-942c-c2ccee3a647b.png)

**Comment by markbrocato** [comment]
My guess is it's failing to load one of the dependencies from Ext JS.  Any chance restarting your webpack watch task fixes it?  (npm start if you're using one of the boilerplates).  Failing that, if you share your project on GitHub I'd be happy to take a look.

**Comment by BlaineBradbury** [comment]
I've got a bunch of stuff in here, so I'll first take a fresh copy of the boilerplate and work from it adding just what is need, and if I reproduce the error, I'll share it out.  thx

**Comment by BlaineBradbury** [comment]
Ok, so I've narrowed it down to failing if my store is a BufferedStore (.Store works fine) and not using the classic toolkit (which I was not).  If I switch to modern, I get the above errors.

To be exact, if I comment out this line in the webpack.config.dev.js file and rebuild:
            toolkit: 'classic',
or change it to:
            toolkit: 'modern',

**Comment by BlaineBradbury** [comment]
Apparently it is a bug:
https://www.sencha.com/forum/showthread.php?335348-Modern-toolkit-Grid-with-BufferedStore
