### ISSUE TITLE
Are ~~PagingToolbar~~ and Searchfield available?

### ISSUE THREAD

**Issue by BlaineBradbury** [sencha/extjs-reactor#66]
Getting:
Uncaught Error: No xtype "pagingtoolbar" found.  Perhaps you need to require it with Ext.require("pagingtoolbar")?

All the others in this import seem to work:

import { Grid, Panel, Tabpanel, Container, SearchField, Pagingtoolbar } from '@extjs/reactor/modern'

re:
                  <Pagingtoolbar
                    store={this.store}
                    displayInfo={true}
                    docked='bottom'
                    displayMsg='Displaying topics {0} - {1} of {2}'
                    emptyMsg='No topics to display'
                  >
                  </Pagingtoolbar>

This works for basic paging...

      Ext.require([
          'Ext.grid.plugin.PagingToolbar'
      ])

      <Grid title="MyGrid" plugins={['pagingtoolbar']}...

...But this doesn't really leave me the same flexibility.

Also, weirdly, the JSX syntax displays a toolbar when the plugin is required and built.

**Comment by markbrocato** [comment]
I was able to add a paging toolbar to the reactor-classic-boilerplate.  Here's my App.js:

```jsx
import React, { Component } from 'react';

import Person from './Person';
import data from './data';
import { Panel, Grid, Toolbar, TextField, PagingToolbar } from '@extjs/reactor/classic';

Ext.require('Ext.window.Toast');

export default class App extends Component {

    constructor(props) {
        super(props);
        
        this.state = {
            person: null
        };

        this.store = Ext.create('Ext.data.Store', {
            data
        });
    }

    onSearch(value) {
        value = value.toLowerCase();
        this.store.clearFilter();
        this.store.filterBy(record => {
            return record.get('name').toLowerCase().indexOf(value) !== -1 ||
                record.get('email').toLowerCase().indexOf(value) !== -1
        });
    }

    onRowClick(person) {
        this.setState({ person });
    }

    onSavePerson(person) {
        Ext.toast(`Person ${person.name} saved.`);
        this.store.getById(person.id).set(person, { dirty: false });
        this.setState({ person: null });
    }

    onPersonDialogClose() {
        this.setState({ person: null });
    }
    
    render() {
        const { person } = this.state;
        
        return (
            <Panel layout="fit" title="Employees">
                { person && (
                    <Person
                        person={person}
                        onSave={person => this.onSavePerson(person)}
                        onClose={() => this.setState({ person: null })}
                    />
                ) }
                <Toolbar dock="top">
                    <TextField emptyText="Search" onChange={(field, value) => this.onSearch(value)} flex={1}/>
                </Toolbar>
                <Grid
                    store={this.store}
                    columns={[
                        { text: 'Name', dataIndex: 'name', flex: 1 },
                        { text: 'Email', dataIndex: 'email', flex: 1 }
                    ]}
                    onRowClick={(grid, record) => this.onRowClick(record.data)}
                >
                    <PagingToolbar dock="bottom"/>
                </Grid>
            </Panel>
        );
    }
}
```

**Comment by AjaxSolutions** [comment]
I see to Toolbar, but why there are violation messages in the console?
<img width="618" alt="screen shot 2017-02-13 at 2 25 08 pm" src="https://cloud.githubusercontent.com/assets/397472/22901777/6756b316-f1f8-11e6-93ec-3518f94ce038.png">

**Comment by markbrocato** [comment]
I'm not sure.  I don't see those.  Have you made any other modifications to reactor-classic-boilerplate?

**Comment by BlaineBradbury** [comment]
Ok, I am able to pull in the Pagingtoolbar, but not Searchfield in the classic boilerplate... I updated the boilerplate locally and it began to work, so I might have been outdated.

After pulling down the latest versions and not adding back Redux or the Router... working just from the boilerplate with the customized Grid, etc... I cannot pull in Searchfield.

import { Grid, Panel, Tabpanel, Pagingtoolbar, Container, Searchfield } from '@extjs/reactor/classic';

error:
Uncaught Error: No xtype "searchfield" found.  Perhaps you need to require it with Ext.require("searchfield")?

If I switch webpack config to:
            toolkit: 'modern',

...it works and does display the Searchfield when loaded.

**Comment by markbrocato** [comment]
SearchField is only available in the modern toolkit.  When using the classic toolkit you can just use TextField instead.
