### ISSUE TITLE
Plugin name is incorrect?

### ISSUE THREAD

**Issue by MoimHossain** [sencha/extjs-reactor#67]
I have tried to run the boilerplate project- it didn't work out of the box- until I have renamed the plugin name from 'columnresizing' to 'gridcolumnresizing'. 

With 'gridcolumnresizing' it worked!

**Comment by markbrocato** [comment]
It looks like gridcolumresizing was renamed to columnresizing in Ext JS 6.2.  If you're running 6.0 I suggest upgrading.
