### ISSUE TITLE
Can't override doDestroy method

### ISSUE THREAD

**Issue by AjaxSolutions** [sencha/extjs-reactor#69]
I should be able to override this method, but an error results.
```
export default Ext.define('Boilerplate.PTOChart', {
    extend: 'Ext.chart.PolarChart',
    ...
    doDestroy: function() {
        debugger;
        this.callParent();
    }
});
```
<img width="608" alt="screen shot 2017-02-14 at 10 08 54 am" src="https://cloud.githubusercontent.com/assets/397472/22937263/b3bad250-f29d-11e6-9b68-c19b219dc5c2.png">

**Comment by AjaxSolutions** [comment]
Let me reword this in another issue.

**Comment by AjaxSolutions** [comment]
I'm going to reopen this issues.  The doDestroy method is marked as public in the modern toolkit, so I should be able to override it.

http://docs.sencha.com/extjs/6.2.1/modern/Ext.Component.html#method-doDestroy

**Comment by AjaxSolutions** [comment]
This works fine in Sencha fiddle, so I think there's an issues with the extjs-reactor(?)

this.callParent.caller is null, and it should not be.
<img width="476" alt="screen shot 2017-02-15 at 10 12 57 am" src="https://cloud.githubusercontent.com/assets/397472/22983684/7dae3d20-f368-11e6-90e8-8d79c4568e56.png">

**Comment by AjaxSolutions** [comment]
I see the code is running in strict mode, so I can't access caller.

**Comment by AjaxSolutions** [comment]
Mark, do you see the issue which I reported as a problem?

**Comment by markbrocato** [comment]
It seems that babel automatically puts all code in strict mode.  You can either use the following instead of callParent...

```javascript
this.self.superclass.doDestroy.apply(this, arguments);
```

...or try this babel plugin to remove strict mode: https://www.npmjs.com/package/babel-plugin-transform-remove-strict-mode

**Comment by AjaxSolutions** [comment]
Thank you!

**Comment by AjaxSolutions** [comment]
I just tried both options, and they worked for me.
