### ISSUE TITLE
Grid scrollbar scrolls to top [classic toolkit]

### ISSUE THREAD

**Issue by BlaineBradbury** [sencha/extjs-reactor#70]
If I am in the classic toolkit and I load a Grid from a regular Store or BufferedStore...
1. It loads fine.
2. Then I drag the vertical scroll bar down on the right and let it go.
3. Then if I click on the scroll bar to drag again or if I click in the scroll area, the scroll bar jumps to the top.

If will then behave as expected without this jump until the browser is refreshed and the grid is reloaded.  If I switch to the modern toolkit, this behavior does not reproduce using the regular Store.

**Comment by AjaxSolutions** [comment]
Are you able to reproduce it in Sencha Fiddle w/o React?

I saw a similar jumping defect in the Grid.

https://www.sencha.com/forum/showthread.php?335344-Grid-scrolling-had-been-totally-broken-by-chrome-56-release

**Comment by BlaineBradbury** [comment]
I'm on a trial and have no used Sencha Fiddle, so I'll see what's possible.  At the least, I can setup locally to use straight extjs when I have a few extra moments.  As it is in the boilerplate, I did, though, try it quickly and it jumps on the first scroll on Chrome 57 and Firefox 51.

Firefox also gave some different notifications (see image).  The last notification seemed interesting, so I read on as it states at:  https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects

...then clarified a bit at: http://stackoverflow.com/questions/37098306/this-site-appears-to-use-a-scroll-linked-positioning-effect-this-may-not-work

I'm not sure if that helps or muddies the water for you.

![image](https://cloud.githubusercontent.com/assets/282549/22982842/41ec088e-f36e-11e6-9327-ab7b84a0b859.png)

**Comment by markbrocato** [comment]
This is a known issue and we're working on a fix.  See this forum post for more info: https://www.sencha.com/forum/showthread.php?335344

**Comment by BlaineBradbury** [comment]
The behavior I am seeing is not the one shown in the video in this bug report.  And mine only happens on first load.  It does not happen after the first "jump".  It also occurs in more than just Chrome.  But, if you still think it is related, we can go that route.
