### ISSUE TITLE
Column renderer nesting record and not rendering font [Classic vs Modern toolkits]

### ISSUE THREAD

**Issue by BlaineBradbury** [sencha/extjs-reactor#71]
I have a column renderer in place on a Grid:

                    columns={[
                        { text: 'Date',  dataIndex: 'display_date' },
                        { text: 'Issuer Name', dataIndex: 'issuer', flex: 1, forceFit: true,
                            renderer: function(value, record) {
// hack for classic toolkit:
record = record.record
                              var rtnVal='';
                              if (Ext.isDefined(record.data.MyID) && record.data.MyID.length > 0 && record.data.IS_MAPPED != true)
                              {   
...more code here...

- If I am built with the classic toolkit, the font change I make in the renderer shows up in yellow (see right side of image below).  But I have to find the record data by looking in "record.record.data..." vs "record.data...".
- If I am built with the modern toolkit, the font change does not render, but instead the actual font code displays in the grid cells (see left side of the image below).  Also, the record data is found as "record.data..." as expected.

![image](https://cloud.githubusercontent.com/assets/282549/22981934/9f671182-f36b-11e6-811f-87aaac632af9.png)

**Comment by markbrocato** [comment]
In the modern toolkit, use the cell config with encodeHtml: false and a renderer function.  For example:

```jsx
<Grid columns={[{
	text: 'Issuer Name', 
	dataIndex: 'issuer', 
	flex: 1, 
	forceFit: true,
	cell: {
		encodeHtml: false,
		renderer: (value, record) => `<div style="color: red">${value}</div>`
	}
}]}/>
```

If you're just looking to style the cell, I suggest using css:

```javascript
cell: { cls: 'some-css-class' }
```

... or style ...

```javascript
cell: { style: { backgroundColor: 'red' } }
```

**Comment by BlaineBradbury** [comment]
1. Thanks.   The encodeHtml config resolves the HTML issue without even moving the renderer... and it works in the classic toolkit (which I must use until the modern toolkit supports a BufferedStore).

2. The issue with the Record being nested is not a show stopper, but it doesn't seem correct does it?  I do notice that if the renderer is inside the cell config as you've shown, it does not show up nested... only if it is directly in the row config... fyi.

**Comment by markbrocato** [comment]
The renderer method signature in classic differs from modern.  The second parameter in classic is a metadata object containing the record, not the record itself.

See http://docs.sencha.com/extjs/6.2.1/classic/Ext.grid.column.Column.html#cfg-renderer
