### ISSUE TITLE
Support Webpack 2

### ISSUE THREAD

**Issue by markbrocato** [sencha/extjs-reactor#74]
Update the reactor-webpack-plugin to support webpack 2 and update boilerplates to use webpack 2.

**Comment by AjaxSolutions** [comment]
React is switching to Rollup

<img width="590" alt="screen shot 2017-03-10 at 6 14 39 am" src="https://cloud.githubusercontent.com/assets/397472/23794998/e04f174a-0558-11e7-923b-51ff4fea702f.png">
