### ISSUE TITLE
Custom theme with webpack 2

### ISSUE THREAD

**Issue by psartini** [sencha/extjs-reactor#95]
Using reactor-material-ui-boilerplate.
99052b87c5f6131ff6b4a57881dda97e97a9fa55: switched to webpack 2 config and does not include './ext-theme' but default 'theme-material'. 

After changing webpack.config.js:
``theme: './ext-theme',``

I get the following error:

> [WRN] Failed to resolve package ext-theme
> [ERR] Theme "ext-theme" not found
> [ERR]
> [ERR] BUILD FAILED
> [ERR] com.sencha.exceptions.BasicException: com.sencha.exceptions.ExNotFound: Required package > "ext-theme" not found

Any solution to this?

**Note: I did not test with webpack 1, just assuming the boilerplate worked before.**

**Comment by markbrocato** [comment]
I just merged a PR that corrects the theme configuration as you described.  It looks like Sencha Cmd 6.5 is required for relative theme paths to work.  You can download the latest nightly from the support portal.

**Comment by psartini** [comment]
confirmed: works with Cmd 6.5.0.25
May I suggest to document this fact in the webpack plugin's readme?

Currently it states:
> You must have Ext JS 6.2+ and Sencha Cmd 6.2+ to use this plugin.

**Comment by markbrocato** [comment]
Done.  As an aside, to my knowledge all of the other configs work with Cmd 6.2, but the bulk of our testing at this point is against Cmd 6.5, so not 100% sure.
