### ISSUE TITLE
Could not create Ext JS component with config

### ISSUE THREAD

**Issue by roberto-slopez** [sencha/extjs-reactor#98]
`import { Panel } from '@extjs/reactor/classic';`
`<Panel title="React Ext JS" height={'100%'}>Hello World!</Panel>`

![image](https://cloud.githubusercontent.com/assets/2015112/24208721/f83ffbd6-0ee9-11e7-8bf5-f6ac4631e2c6.png)
![image](https://cloud.githubusercontent.com/assets/2015112/24208922/79a0e618-0eea-11e7-8756-959f77f5f23d.png)

**Comment by markbrocato** [comment]
That code looks fine, so it's probably a configuration issue.  Can you verify that you're using the latest release of Ext JS (6.2.1) and Sencha Cmd (6.2.2)?  If so, what does your webpack config look like?

**Comment by roberto-slopez** [comment]
- **Sencha Cmd**:  *v6.2.2.36*
- **ExtJS**: `{"version":"6.2.1.167","pad":0,"shortVersion":"621167","releaseValue":0,"parts":[6,2,1,167],"major":6,"minor":2,"patch":1,"build":167}`
- **webpack config**: 
```// jshint esversion:6
const webpack = require('webpack');
const ExtJSReactorWebpackPlugin = require('@extjs/reactor-webpack-plugin');
module.exports = {
    entry: './board/main.js',
    output: {
        filename: 'board.js',
        path: '\\resources\\lib',
        libraryTarget: "var",
        library: "Board"
    },
    module: {
        loaders: [
            {
                text: /\.jsx?$/,
                loader: 'babel',
                exclude: /node_modules/,
                query: {
                    presets: ['es2016', 'es2017', 'react'],
                    plugins: ['transform-es2015-modules-commonjs', "@extjs/reactor-babel-plugin"]
                }
            }
        ]
    },
    target: 'node',
    plugins: [
        new webpack.DefinePlugin({
            "process.env": {
                NODE_ENV: JSON.stringify("production")
            }
        }),
        new ExtJSReactorWebpackPlugin({
            sdk: './ext',
            theme: 'theme-triton',
            toolkit: 'classic',
            packages: ['charts']
        })
    ]
};
```

**Comment by markbrocato** [comment]
How are you loading the Ext js and css bundles?  For example in reactor-classic-boilerplate we use HtmlWebpackPlugin: https://github.com/sencha/extjs-reactor/blob/master/packages/reactor-classic-boilerplate/webpack.config.js#L45

**Comment by roberto-slopez** [comment]
I build librerary, in reactjs with components extjsreactor, this lib is begin used in proyect with extjs6.2, I need add on app.json load ext.js and ext.css ?

**Comment by markbrocato** [comment]
Closing this as we chatted on gitter.
